"""
Event Definitions for the Event-Driven Trading Architecture.

The event system forms the backbone of the ATS execution loop.
All components communicate exclusively through events placed on a central queue.

Event Flow:
    MarketDataEvent → SignalEvent → OrderEvent → FillEvent

Reference: Blueprint Section "The Fidelity of Event-Driven Systems"
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any, Dict, Optional


# ============================================
# Base Event
# ============================================

class EventType(Enum):
    """Types of events flowing through the system."""
    MARKET_DATA = auto()
    SIGNAL = auto()
    ORDER = auto()
    FILL = auto()
    RISK_ALERT = auto()
    KILL_SWITCH = auto()
    SYSTEM = auto()


@dataclass
class Event:
    """
    Base event class. All events in the system derive from this.
    
    Every component communicates strictly by placing Event objects
    onto the central event queue (collections.deque).
    """
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = EventType.SYSTEM
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __repr__(self) -> str:
        return (
            f"<{self.__class__.__name__} "
            f"id={self.event_id[:8]}... "
            f"type={self.event_type.name} "
            f"at={self.timestamp.isoformat()}>"
        )


# ============================================
# Market Data Events
# ============================================

class TickType(Enum):
    """Type of market tick."""
    TRADE = "trade"
    BID = "bid"
    ASK = "ask"


@dataclass
class MarketDataEvent(Event):
    """
    Generated by the Data Handler when new tick/bar data arrives.
    
    This is the entry point of the event loop. The data handler creates
    a MarketDataEvent timestamped to the millisecond, pushed to the queue.
    """
    event_type: EventType = EventType.MARKET_DATA
    symbol: str = ""
    price: float = 0.0
    volume: float = 0.0
    tick_type: TickType = TickType.TRADE
    bid: float = 0.0
    ask: float = 0.0
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    timeframe: str = ""  # "1m", "5m", "1h", "1d" for bar data


# ============================================
# Signal Events
# ============================================

class SignalDirection(Enum):
    """Direction of a trading signal."""
    LONG = "long"
    SHORT = "short"
    EXIT = "exit"


@dataclass
class SignalEvent(Event):
    """
    Generated by the Strategy Engine after evaluating market data.
    
    Contains the ticker symbol, timestamp, expected direction (long/short),
    and a confidence strength multiplier (0.0 to 1.0).
    """
    event_type: EventType = EventType.SIGNAL
    symbol: str = ""
    direction: SignalDirection = SignalDirection.LONG
    strength: float = 0.0  # 0.0 to 1.0 confidence
    strategy_name: str = ""
    indicators: Dict[str, float] = field(default_factory=dict)


# ============================================
# Order Events
# ============================================

class OrderType(Enum):
    """Type of order to be placed."""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class OrderSide(Enum):
    """Side of the order."""
    BUY = "buy"
    SELL = "sell"


@dataclass
class OrderEvent(Event):
    """
    Generated by the Risk Management module after evaluating a SignalEvent.
    
    Specifies the order type (Market, Limit, Stop) and exact share quantity
    after position sizing and risk checks.
    """
    event_type: EventType = EventType.ORDER
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    strategy_name: str = ""
    signal_id: str = ""  # Reference to originating signal


# ============================================
# Fill Events
# ============================================

class FillStatus(Enum):
    """Status of an order fill."""
    FILLED = "filled"
    PARTIAL = "partial"
    REJECTED = "rejected"
    CANCELLED = "cancelled"


@dataclass
class FillEvent(Event):
    """
    Generated by the Execution Handler after order execution.
    
    Models realistic slippage, calculates brokerage commissions, and
    officially updates the portfolio's cash and holding balances.
    """
    event_type: EventType = EventType.FILL
    order_id: str = ""
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    filled_quantity: float = 0.0
    fill_price: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    status: FillStatus = FillStatus.FILLED
    broker: str = ""


# ============================================
# System Events
# ============================================

@dataclass
class KillSwitchEvent(Event):
    """Emergency kill switch activation event."""
    event_type: EventType = EventType.KILL_SWITCH
    activated: bool = True
    reason: str = ""
    activated_by: str = "system"


@dataclass
class RiskAlertEvent(Event):
    """Risk alert when limits are approaching or breached."""
    event_type: EventType = EventType.RISK_ALERT
    alert_level: str = "warning"  # "warning", "critical", "emergency"
    message: str = ""
    current_value: float = 0.0
    threshold: float = 0.0
